module.exports.VAULT_CONSTANTS = {
    POSTGRESQL_HOST: 'POSTGRESQL_HOST',
    POSTGRESQL_PORT: 'POSTGRESQL_PORT',
    POSTGRESQL_USER: 'POSTGRESQL-USER',
    POSTGRESQL_PASSWORD: 'POSTGRESQL-PASSWORD',
    POSTGRESQL_DATABASE: 'POSTGRESQL-DATABASE'
}